<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "smile_t3_toolkit"
 *
 * Auto generated by Extension Builder 2016-11-05
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'TYPO3 Toolkit',
    'description' => 'A toolkit for TYPO3 website.',
    'category' => 'plugin',
    'author' => 'Rolel',
    'author_email' => 'typo3@smile.fr',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '7.6.0-7.6.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
